# https://github.com/release-drafter/release-drafter
autolabeler:
  - label: bug
    branch: [/^(bug|bugfix|fix|hotfix)\/.*/]
  - label: changelog:skip
    branch: [/^(dependabot)\/.*/, /^pre-commit-ci-update-config/, /^renovate\/.*lockfile/]
  - label: dependencies
    branch: [/^(depend|dependabot|renovate)\/.*/, /^pre-commit-ci-update-config/]
  - label: documentation
    branch: [/^(docs)\/.*/]
  - label: feature
    branch: [/^(enhancement|feat|feature)\/.*/]
  - label: maintenance
    branch: [/^(chore|maint|maintain|maintenance)\/.*/, /^pre-commit-ci-update-config/]
  - label: changelog:patch
    branch: [/^(bug|bugfix|fix|hotfix)\/.*/]
  - label: release
    branch: [/^(release)\/.*/]
categories:
  - title: ðŸš€ Features
    labels:
      - feature
      - enhancement
  - title: ðŸ› Bug Fixes
    labels:
      - bug
  - title: ðŸ§¶ Dependencies
    labels:
      - dependencies
  - title: ðŸ“– Doc Updates
    labels:
      - documentation
  - title: ðŸ§° Maintenance
    label: maintenance
category-template: >-
  ### $TITLE
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
commitish: master  # cspell:ignore commitish
exclude-contributors:
  - dependabot
  - renovate
exclude-labels:
  - changelog:skip
  - release
name-template: v$RESOLVED_VERSION
sort-direction: ascending
tag-template: v$RESOLVED_VERSION
template: |
  ## What Changed

  $CHANGES
version-resolver:
  major:
    labels:
      - changelog:major
  minor:
    labels:
      - changelog:minor
  patch:
    labels:
      - changelog:patch
  default: patch
